name: test
on:
  push: null

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: beckermr/provision-with-micromamba@main

      - name: run python
        shell: bash -l {0}
        run: |
          cat ~/.profile
          echo `which python`
          python -c "import numpy"
